### PR TITLE
Fix for Issue #7

### PR DESCRIPTION
**Pull request by reddigfabian**
Get an error on a missing EZ method in Toaster. Left a FIXME.
Fixed subscriptions to single devices by adding on the "/events" path piece in EventsDelegate's URI builder.

### CODE REVIEW

**Comment by reddigfabian** [comment]
Not sure why all those .iml files got pulled into this. I can resubmit if necessary.

**Comment by jensck** [comment]
Nice catch, thanks for the patch!

Have you filled out the Particle CLA?  If not, it's available here: https://goo.gl/fGM9KD

**Comment by reddigfabian** [comment]
Just did. Really excited to have this working. I just got a second Photon and am looking forward to experimenting further.

**Comment by jensck** [comment]
Merged.  Thanks again @reddigfabian !

**Pull request merged**
