### PR TITLE
add setUser

### PR DESCRIPTION
**Pull request by brandongoode**

### CODE REVIEW

**Comment by idokleinman** [comment]
Is this for enabling 2 legged auth?

**Comment by brandongoode** [comment]
That is the idea.  This is what I was thinking.  There is probably a more elegant way, but this works for me.

``` java
        ParticleCloud particleCloud = ParticleCloudSDK.getCloud();

        ParticleUser particleUser = ParticleUser.fromNewCredentials(mUserEmail, "placeholder");
        particleCloud.setUser(particleUser);

        long expirationMillis = response.expiresInSeconds * 1000;
        Date expirationDate = new Date(System.currentTimeMillis() + expirationMillis);
        particleCloud.setAccessToken(response.accessToken, expirationDate);

        ParticleDeviceSetupLibrary.startDeviceSetup(this);
```

**Comment by jensck** [comment]
@brandongoode thanks for the patch!

I'm trying to figure out what the right thing is with this API.  I'll include this in the list of potential solutions I review this weekend.

**Comment by brandongoode** [comment]
Other option would be to allow custom `IdentityApi` to be defined and set for the `ParticleCloud` instance.  This would allow me to just us deviceSetup for everything: login, signup, and password reset.

**Comment by brandongoode** [comment]
Added setIdentityApi to allow for a custom 2 leg auth. 

Here's what I have working.

``` java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ParticleDeviceSetupLibrary.init(this.getApplicationContext(), MainActivity.class);

        ParticleCloud particleCloud = ParticleCloudSDK.getCloud();

        particleCloud.setIdentityApi(new CustomIdentityApi());

    }

    @Override
    protected void onStart() {
        super.onStart();
        ParticleDeviceSetupLibrary.startDeviceSetup(this);
    }

```

``` java
public class CustomIdentityApi implements ApiDefs.IdentityApi {

    private static final String SIGN_IN_URL = "https://api.automategreen.com/v1/signin";
    private static final String FORGOT_URL = "https://app.automategreen.com/forgot";
    private static final String PARTICLE_TOKEN_URL = "https://api.automategreen.com/v1/tokens/particle";

    private String mAccessToken = null;

    public CustomIdentityApi() {

    }

    @Override
    public Response signUp(String username, String password) {
        return null;
    }

    @Override
    public Responses.LogInResponse signUpAndLogInWithCustomer(String grantType, String email, String password, String orgSlug) {
        return null;
    }

    @Override
    public Responses.LogInResponse logIn(String grantType, String username, String password) {
        mAccessToken = null;
        Responses.LogInResponse response = null;

        try {
            JSONObject user = new JSONObject();
            user.put("email", username);
            user.put("password", password);

            JSONObject params = new JSONObject();
            params.put("user", user);
            params.put("desc", "Device Config App");

            JSONObject loginResponse = post(SIGN_IN_URL, params);

            if(loginResponse == null) {
                return null;
            }

            mAccessToken = loginResponse.getString("token");

            JSONObject token = post(PARTICLE_TOKEN_URL, null);

            response = new Responses.LogInResponse(
                    token.getLong("expires_in"),
                    token.getString("access_token"),
                    token.getString("token_type")
            );
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return response;
    }

    @Override
    public Response requestPasswordReset(String email) {
        mAccessToken = null;
        Responses.LogInResponse response = null;

        try {
            JSONObject user = new JSONObject();
            user.put("email", email);

            JSONObject loginResponse = post(FORGOT_URL, user);

        } catch (JSONException e) {
            e.printStackTrace();
        }

        return null;
    }


    private JSONObject post(String urlString, JSONObject jsonParam) {
        HttpURLConnection conn = null;
        StringBuilder result = new StringBuilder();
        try{
            URL url = new URL(urlString);
            conn = (HttpURLConnection) url.openConnection();
            conn.setReadTimeout(10000 /* milliseconds */);
            conn.setConnectTimeout(15000 /* milliseconds */);
            conn.setRequestMethod("POST");
            conn.setDoInput(true);
            if(jsonParam != null) {
                conn.setDoOutput(true);
            }
            conn.setUseCaches(false);
            conn.setRequestProperty("Content-Type", "application/json");
            if(mAccessToken != null) {
                conn.setRequestProperty("Authorization", "Bearer " + mAccessToken);
            }
            // Starts the query
            conn.connect();

            if(jsonParam != null) {
                OutputStreamWriter wr = new OutputStreamWriter(conn.getOutputStream());
                wr.write(jsonParam.toString());
                wr.flush();
                wr.close();
            }


            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));


            String line;
            while ((line = reader.readLine()) != null) {
                result.append(line);
            }
        } catch (MalformedURLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally {
            if (conn != null) {
                try {
                    conn.disconnect();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }

        try {
            return new JSONObject(result.toString());
        } catch (JSONException e) {
            e.printStackTrace();
            return null;
        }
    }
}
```

**Comment by ghost** [comment]
What's the status on this? I don't think I'm able to 'login' with the user name and the accessToken with the current library, but if this pull request I can call .setAccessToken() and then .setUser() for the user name

**Comment by jensck** [comment]
The iOS SDK has some new identity/auth API changes that I intend to
implement soon.  That change will include the ability to set a user name.

On Thu, Apr 28, 2016, 09:11 Marcio notifications@github.com wrote:

> What's the status on this? I don't think I'm able to 'login' with the user
> name and the accessToken with the current library, but if this pull request
> I can call .setAccessToken() and then .setUser() for the user name
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/spark/spark-sdk-android/pull/9#issuecomment-215435657
> 
> ## 

Jens Knutson

Sent from my Nexus

**Comment by idokleinman** [comment]
I implemented `injectAccessToken()` on iOS - username has no meaning when you are authenticated via a two legged process. Can you explain your need @marcio-granzotto-ckl ?

**Comment by idokleinman** [comment]
@jensck whats the verdict on this one? Should we close it?

**Pull request closed without merging**
