### PR TITLE
Session token release

### PR DESCRIPTION
**Pull request by CityVibes**
0.4.6 Cloud sdk release adding previously developed but unreleased refresh and inject session token methods. #21 #29 
Also updating Android dependencies

### CODE REVIEW

**Comment by idokleinman** [comment]
I only see changes to meta/config files in this PR, where's the actual code change? Am I missing something?

**Comment by CityVibes** [comment]
Code changed a while ago, did not release it right away as there was need to look it over few more times. Code I am referring to is #45 
Basically this is just meta update to release non-released code prior to setup update.

**Comment by CityVibes** [comment]
@idokleinman adding catch clause for crash exception

**Comment by idokleinman** [comment]
Any idea why the exception was happening in the first place?

**Comment by CityVibes** [comment]
@idokleinman Unsure at the moment, exception happens within networking library, could be something in its configuration.

**Review by idokleinman — APPROVED** [review]

**Pull request merged**
